<script lang="ts">
  import './styles.scss';
  import './prism-gruvbox-dark.css';
  import { darkMode, displayMode, lightMode } from '$lib/stores/displayMode';
  import Header from '$lib/components/Header.svelte';

  let title = `Switch to light mode`;
  let icon = '🌚';
  let mode = darkMode;

  displayMode.mode.subscribe((m) => {
    mode = m;
    title = `Switch to ${m === lightMode ? 'dark' : 'light'} mode`;
    icon = m === darkMode ? '🌞' : '🌚';
  });
</script>

<svelte:head>
  {#if mode === lightMode}
    <style>
      :root {
        --bg-color: #ffedcf;
        --text-color: #253131;
        --link-color: #1b7650;
        --link-visited-color: #136433;
        --border-color: #253131;
        /*
        * Filter for coloring SVGs loaded through <img> tags
        * Filter generated by this tool https://codepen.io/sosuke/pen/Pjoqqp
        */
        --svg-filter: invert(12%) sepia(18%) saturate(645%) hue-rotate(131deg) brightness(99%)
          contrast(85%);
        --yellow-color: #e7b912;
        --block-quote-bg-color: #fff4e1;
      }
    </style>
  {:else}
    <style>
      :root {
        --bg-color: #253131;
        --text-color: #ffe8c3;
        --link-color: #85ffb5;
        --link-visited-color: #73c0a0;
        --border-color: #ffe8c3;
        /*
        * Filter for coloring SVGs loaded through <img> tags
        * Filter generated by this tool https://codepen.io/sosuke/pen/Pjoqqp
        */
        --svg-filter: invert(90%) sepia(8%) saturate(1537%) hue-rotate(325deg) brightness(107%)
          contrast(102%);
        --yellow-color: #ffedcf;
        --block-quote-bg-color: rgba(0, 0, 0, 0.1);
      }
    </style>
  {/if}
</svelte:head>

<Header />
<slot />

<button on:click={displayMode.toggle} class="light-switch" {title}>
  {icon}
</button>

<style lang="scss">
  .light-switch {
    font-size: 1.5rem;
    position: fixed;
    bottom: 0;
    left: 0;
    width: 3rem;
    height: 3rem;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    z-index: 100;
    opacity: 0.6;
    transition: opacity 0.2s;
    background-color: transparent;
    border: none;
  }

  .light-switch:hover {
    opacity: 1;
  }
</style>
