graph TD;
    YourPlace-->TheAlley;
    YourPlace-->ElkStreet;
    TheAlley-->ByTheWater;
    TheAlley-->TheTavern;
    ElkStreet-->TheTavern;
    ElkStreet-->MooseStreet;
    ByTheWater-->TheDock;
    ByTheWater-->MerchantsPlaza;
    TheTavern-->MerchantsPlaza;
    TheTavern-->KingsPlaza;
    MooseStreet-->KingsPlaza;
    MooseStreet-->CaribouStreet;
    TheDock-->TheGetawayBoat;
    TheDock-->ThePortOffice;
    MerchantsPlaza-->ThePortOffice;
    MerchantsPlaza-->YourPlace;
    KingsPlaza-->YourPlace;
    KingsPlaza-->TheGetawayCar;
    CaribouStreet-->TheGetawayCar;
    CaribouStreet-->ReindeerStreet;