import { cloneArticulatedLeg2 } from '../articulatedLeg';
import type { GenerateInsectaOptions, InsectaSpeciesId } from './types';
import { INSECTA_INITIAL_LEGS } from './insectaInitialLegs';

/** Full option bundles per species preset (tool panel applies these). */
export const INSECTA_SPECIES_DEFAULTS: Record<InsectaSpeciesId, GenerateInsectaOptions> = {
  bee: {
    species: 'bee',
    /* Chunky thorax + long abdomen with taper (stinger); small head. Wings mostly along the body
     * axis so from above they read as folded on the back, not stuck out sideways. */
    totalLength: 30,
    headRatio: 17,
    thoraxRatio: 28,
    abdomenRatio: 55,
    bodyHalfWidth: 4,
    bodyHalfHeight: 4,
    abdomenTaper: 0.48,
    headShape: 75,
    anchorOffsetU: 0,
    anchorOffsetV: 0,
    bodyYaw: 0,
    bodyArch: 0.05,
    legFront: cloneArticulatedLeg2(INSECTA_INITIAL_LEGS.front),
    legMid: cloneArticulatedLeg2(INSECTA_INITIAL_LEGS.mid),
    legHind: cloneArticulatedLeg2(INSECTA_INITIAL_LEGS.hind),
    antennaLength: 5,
    antennaSpread: 12,
    antennaPitch: 18,
    antennaRoot: 2,
    mandibleLength: 2,
    mandibleSpread: 9,
    mandibleForward: 1,
    wingShape: 85,
    showWingFore: true,
    wingForeLength: 15,
    wingForeWidth: 4,
    wingForeSpread: 78,
    wingForeForwardCant: 5,
    wingForePitch: 5,
    wingForeOffset: 1,
    showWingHind: true,
    wingHindLength: 12,
    wingHindWidth: 3,
    wingHindSpread: 72,
    wingHindPitch: 4,
    wingHindOffset: -1
  },
  dragonfly: {
    species: 'dragonfly',
    /* Tiny head, compact flight-muscle thorax, very long slender abdomen; wings stick out sideways
     * (low spread), not folded along the body like a bee. */
    totalLength: 52,
    headRatio: 8,
    thoraxRatio: 28,
    abdomenRatio: 64,
    bodyHalfWidth: 1,
    bodyHalfHeight: 2,
    abdomenTaper: 0.58,
    headShape: 35,
    anchorOffsetU: 0,
    anchorOffsetV: 0,
    bodyYaw: 0,
    bodyArch: 0.02,
    legFront: {
      enabled: true,
      hipU: 4,
      hipV: 0,
      knee: [0, 2, -2],
      foot: [1, 2, -4],
      femurRib: false
    },
    legMid: {
      enabled: true,
      hipU: 1,
      hipV: 0,
      knee: [1, 2, -3],
      foot: [1, 2, -4],
      femurRib: false
    },
    legHind: {
      enabled: true,
      hipU: -1,
      hipV: 0,
      knee: [0, 2, -2],
      foot: [1, 2, -4],
      femurRib: false
    },
    antennaLength: 2,
    antennaSpread: 10,
    antennaPitch: 12,
    antennaRoot: 1,
    mandibleLength: 1,
    mandibleSpread: 5,
    mandibleForward: 1,
    wingShape: 90,
    showWingFore: true,
    wingForeLength: 28,
    wingForeWidth: 2,
    wingForeSpread: 7,
    wingForeForwardCant: 16,
    wingForePitch: 14,
    wingForeOffset: 1,
    showWingHind: true,
    wingHindLength: 26,
    wingHindWidth: 2,
    wingHindSpread: 18,
    wingHindPitch: 12,
    wingHindOffset: 4
  },
  grasshopper: {
    species: 'grasshopper',
    /* Large pronotum/thorax, long hind femora, very long filiform antennae; tegmina fold along
     * abdomen (high wing spread). Slight “hunched” arch. */
    totalLength: 40,
    headRatio: 14,
    thoraxRatio: 40,
    abdomenRatio: 46,
    bodyHalfWidth: 3,
    bodyHalfHeight: 3,
    abdomenTaper: 0.34,
    headShape: 50,
    anchorOffsetU: 0,
    anchorOffsetV: 0,
    bodyYaw: 0,
    bodyArch: -0.1,
    legFront: {
      enabled: true,
      hipU: -5,
      hipV: 0,
      knee: [1, 2, -4],
      foot: [1, 2, -5],
      femurRib: false
    },
    legMid: {
      enabled: true,
      hipU: 1,
      hipV: 0,
      knee: [2, 3, -5],
      foot: [2, 2, -5],
      femurRib: false
    },
    legHind: {
      enabled: true,
      hipU: 6,
      hipV: 0,
      /* Femur: more +f/+s, less +u than before so thighs clear tegmina; then tibia + tarsus. */
      knee: [5, 7, 4],
      foot: [2, 1, -11],
      tarsus: [5, 0, -1],
      femurRib: true
    },
    antennaLength: 22,
    antennaSpread: 10,
    antennaPitch: 18,
    antennaRoot: 2,
    mandibleLength: 2,
    mandibleSpread: 8,
    mandibleForward: 1,
    wingShape: 75,
    showWingFore: true,
    wingForeLength: 16,
    wingForeWidth: 2,
    wingForeSpread: 74,
    wingForeForwardCant: 0,
    wingForePitch: 7,
    wingForeOffset: 0,
    showWingHind: true,
    wingHindLength: 14,
    wingHindWidth: 2,
    wingHindSpread: 70,
    wingHindPitch: 5,
    wingHindOffset: -1
  },
  fly: {
    species: 'fly',
    /* Huge compound-eye head, compact humped thorax, short soft abdomen; one main wing pair
     * (hind pair reduced to small haltere-like stubs in this voxel model). */
    totalLength: 22,
    headRatio: 48,
    thoraxRatio: 30,
    abdomenRatio: 22,
    bodyHalfWidth: 3,
    bodyHalfHeight: 3,
    abdomenTaper: 0.22,
    /* Higher headShape → lateral cheek bulge in segmentRadii; pairs with pipeline compound-eye slabs. */
    headShape: 52,
    anchorOffsetU: 0,
    anchorOffsetV: 0,
    bodyYaw: 0,
    bodyArch: 0.04,
    legFront: {
      enabled: true,
      /* Hips toward −f (head): large head + short thorax read better with legs under thorax, not abdomen. */
      hipU: -1,
      hipV: 0,
      knee: [1, 2, -2],
      foot: [1, 2, -4],
      femurRib: false
    },
    legMid: {
      enabled: true,
      hipU: -3,
      hipV: 0,
      knee: [1, 2, -3],
      foot: [1, 2, -5],
      femurRib: false
    },
    legHind: {
      enabled: true,
      hipU: -5,
      hipV: 0,
      knee: [1, 2, -3],
      foot: [1, 2, -5],
      femurRib: false
    },
    antennaLength: 2,
    antennaSpread: 18,
    antennaPitch: 38,
    antennaRoot: 1,
    mandibleLength: 1,
    mandibleSpread: 10,
    mandibleForward: 1,
    wingShape: 80,
    showWingFore: true,
    wingForeLength: 13,
    wingForeWidth: 3,
    wingForeSpread: 76,
    wingForeForwardCant: 6,
    wingForePitch: 9,
    wingForeOffset: -3,
    showWingHind: true,
    wingHindLength: 3,
    wingHindWidth: 1,
    wingHindSpread: 55,
    wingHindPitch: 18,
    wingHindOffset: -4
  },
  junebug: {
    species: 'junebug',
    /* Scarab: small head tucked under pronotum, convex oval body, hardened elytra folded tight
     * along abdomen (very high spread), short legs, clubbed antennae. */
    totalLength: 24,
    headRatio: 10,
    thoraxRatio: 38,
    abdomenRatio: 52,
    bodyHalfWidth: 4,
    bodyHalfHeight: 3,
    abdomenTaper: 0.18,
    headShape: 55,
    anchorOffsetU: 0,
    anchorOffsetV: 0,
    bodyYaw: 0,
    bodyArch: 0.08,
    legFront: {
      enabled: true,
      hipU: -2,
      hipV: 0,
      knee: [-1, 5, -3],
      foot: [0, 3, -5],
      femurRib: false
    },
    legMid: {
      enabled: true,
      hipU: 1,
      hipV: 0,
      knee: [0, 6, -3],
      foot: [1, 3, -6],
      femurRib: false
    },
    legHind: {
      enabled: true,
      hipU: 3,
      hipV: 0,
      knee: [2, 6, -2],
      foot: [1, 4, -7],
      femurRib: false
    },
    antennaLength: 3,
    antennaSpread: 14,
    antennaPitch: 22,
    antennaRoot: 1,
    mandibleLength: 1,
    mandibleSpread: 6,
    mandibleForward: 1,
    wingShape: 20,
    showWingFore: true,
    wingForeLength: 12,
    wingForeWidth: 3,
    wingForeSpread: 82,
    wingForeForwardCant: 0,
    wingForePitch: 3,
    wingForeOffset: 1,
    showWingHind: false,
    wingHindLength: 4,
    wingHindWidth: 2,
    wingHindSpread: 24,
    wingHindPitch: 18,
    wingHindOffset: -1
  }
};
